# Generated by Django 3.0.5 on 2020-04-19 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odin_inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='category',
            name='user_created',
            field=models.CharField(editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='category',
            name='user_updated',
            field=models.CharField(editable=False, max_length=30),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_created', models.CharField(editable=False, max_length=30)),
                ('user_updated', models.CharField(editable=False, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripción')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='odin_inventory.Category')),
            ],
            options={
                'verbose_name_plural': 'SubCategorias',
            },
        ),
    ]
