# Generated by Django 3.0.5 on 2020-04-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('odin_security', '0002_auto_20200419_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menumodel',
            name='group',
            field=models.ManyToManyField(related_name='groups', to='auth.Group', verbose_name='Lista de Roles'),
        ),
    ]
